name: Deploy to Github.io

on: 
  push:
    branches:
      - code

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Build and Deploy
        uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: code # The branch the action should deploy from.
          BRANCH: pages # The branch the action should deploy to.
          BUILD_DIR: dist/ # The folder, the action should deploy.
          BUILD_SCRIPT: npm install && npm run build # The build script the action should run prior to deploying.
